# Generated by Django 2.1.5 on 2019-03-18 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wallpaper',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('author', models.CharField(max_length=128)),
                ('title', models.CharField(max_length=128)),
                ('category', models.CharField(max_length=32)),
                ('popularity_source', models.IntegerField()),
                ('popularity_app', models.IntegerField()),
                ('source_url', models.CharField(max_length=256)),
                ('image_full_url', models.CharField(max_length=256)),
                ('image_full_width', models.IntegerField()),
                ('image_full_height', models.IntegerField()),
                ('image_thumbnail_url', models.CharField(max_length=256)),
                ('image_thumbnail_width', models.IntegerField()),
                ('image_thumbnail_height', models.IntegerField()),
                ('image_source_url', models.CharField(max_length=256)),
                ('image_source_width', models.IntegerField()),
                ('image_source_height', models.IntegerField()),
                ('image_source_md5', models.CharField(blank=True, max_length=40, null=True)),
            ],
        ),
        migrations.AddIndex(
            model_name='wallpaper',
            index=models.Index(fields=['image_source_url'], name='hideyhole_w_image_s_2bc178_idx'),
        ),
        migrations.AddIndex(
            model_name='wallpaper',
            index=models.Index(fields=['image_source_md5'], name='hideyhole_w_image_s_233a69_idx'),
        ),
    ]
