# Generated by Django 2.1.5 on 2019-03-18 16:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hideyhole', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallpaper',
            name='added',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
