# Generated by Django 2.1.5 on 2019-03-18 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hideyhole', '0002_wallpaper_added'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannedUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=256)),
            ],
        ),
        migrations.AddIndex(
            model_name='bannedurl',
            index=models.Index(fields=['url'], name='hideyhole_b_url_49e491_idx'),
        ),
    ]
