# Generated by Django 2.1.5 on 2019-03-18 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hideyhole', '0003_auto_20190318_2008'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='wallpaper',
            name='hideyhole_w_image_s_233a69_idx',
        ),
        migrations.RenameField(
            model_name='wallpaper',
            old_name='image_source_md5',
            new_name='image_source_sha1',
        ),
        migrations.AddIndex(
            model_name='wallpaper',
            index=models.Index(fields=['image_source_sha1'], name='hideyhole_w_image_s_e27c01_idx'),
        ),
    ]
