# Generated by Django 2.1.5 on 2019-03-18 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hideyhole', '0005_auto_20190318_2041'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='bannedurl',
            name='hideyhole_b_url_49e491_idx',
        ),
        migrations.RemoveIndex(
            model_name='wallpaper',
            name='hideyhole_w_image_s_2bc178_idx',
        ),
        migrations.RemoveIndex(
            model_name='wallpaper',
            name='hideyhole_w_image_s_e27c01_idx',
        ),
        migrations.AlterField(
            model_name='bannedurl',
            name='url',
            field=models.CharField(max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='wallpaper',
            name='image_source_sha1',
            field=models.CharField(max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='wallpaper',
            name='image_source_url',
            field=models.CharField(max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='wallpaper',
            name='source_url',
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
