# Generated by Django 2.1.5 on 2019-03-18 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hideyhole', '0007_auto_20190318_2115'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='wallpaper',
            index=models.Index(fields=['-added'], name='hideyhole_w_added_cea05b_idx'),
        ),
    ]
