# Generated by Django 2.1.5 on 2019-03-19 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hideyhole', '0008_auto_20190318_2150'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallpaper',
            name='popularity_total',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='wallpaper',
            index=models.Index(fields=['-popularity_total'], name='hideyhole_w_popular_1745ce_idx'),
        ),
    ]
